[package]
name = "fungible2"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[dependencies]
futures = "0.3.17"
async-trait = "0.1.52"
bcs = "0.1.3"
fungible = { path = "../fungible" }
linera-sdk = { path = "../../linera-sdk" }
linera-views = { path = "../../linera-views" }
thiserror = "1.0.31"

[[bin]]
name = "fungible2_contract"
path = "src/contract.rs"

[[bin]]
name = "fungible2_service"
path = "src/service.rs"
