[package]
name = "controller"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[dependencies]
async-graphql = { workspace = true, default-features = false }
bcs.workspace = true
futures.workspace = true
linera-sdk.workspace = true
log.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
linera-sdk = { workspace = true, features = ["test", "wasmer"] }
tokio = { workspace = true, features = ["rt", "sync"] }

[[bin]]
name = "controller_contract"
path = "src/contract.rs"

[[bin]]
name = "controller_service"
path = "src/service.rs"
