[package]
name = "linera-version"
readme = "README.md"
documentation = "https://docs.rs/linera-rpc/latest/linera_rpc/"
description = "Crate version management for the Linera protocol"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-graphql.workspace = true
async-graphql-derive.workspace = true
base64.workspace = true
cargo_metadata.workspace = true
glob.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha3.workspace = true
thiserror.workspace = true
tracing.workspace = true

[build-dependencies]
base64.workspace = true
cargo_metadata.workspace = true
glob.workspace = true
quote.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha3.workspace = true
thiserror.workspace = true

[package.metadata.cargo-machete]
ignored = ["async-graphql-derive"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(linera_version_building)'] }
