[package]
name = "linera-version"
version = "0.10.2"
authors = ["Linera <contact@linera.io>"]
readme = "README.md"
repository = "https://github.com/linera-io/linera-protocol"
homepage = "https://linera.dev"
documentation = "https://docs.rs/linera-rpc/latest/linera_rpc/"
description = "Crate version management for the Linera protocol"
license = "Apache-2.0"
edition = "2021"

[dependencies]
async-graphql.workspace = true
async-graphql-derive.workspace = true
base64.workspace = true
cargo_metadata.workspace = true
glob.workspace = true
once_cell.workspace = true
semver.workspace = true
serde.workspace = true
sha3.workspace = true
thiserror.workspace = true
tracing.workspace = true

[build-dependencies]
base64.workspace = true
cargo_metadata.workspace = true
glob.workspace = true
quote.workspace = true
semver.workspace = true
sha3.workspace = true
thiserror.workspace = true

[package.metadata.cargo-machete]
ignored = ["async-graphql-derive"]
