[package]
name = "linera-views-derive"
version = "0.11.0"
description = "The procedural macros for the crate `linera-views`"
authors = ["Linera <contact@linera.io>"]
repository = "https://github.com/linera-io/linera-protocol"
homepage = "https://linera.dev"
license = "Apache-2.0"
edition = "2021"

[features]
metrics = []

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full", "extra-traits"] }

[dev-dependencies]
insta.workspace = true
prettyplease.workspace = true

[build-dependencies]
cfg_aliases.workspace = true
