[package]
name = "linera-witty-test-modules"
description = "Generation of WIT compatible host code from Rust code"
authors = ["Linera <contact@linera.io>"]
repository = "https://github.com/linera-io/linera-protocol"
homepage = "https://linera.dev"
license = "Apache-2.0"
version = "0.10.0"
edition = "2021"

[[bin]]
name = "export-simple-function"
path = "src/export/simple_function.rs"

[[bin]]
name = "export-getters"
path = "src/export/getters.rs"

[[bin]]
name = "export-setters"
path = "src/export/setters.rs"

[[bin]]
name = "export-operations"
path = "src/export/operations.rs"

[[bin]]
name = "import-simple-function"
path = "src/import/simple_function.rs"

[[bin]]
name = "import-getters"
path = "src/import/getters.rs"

[[bin]]
name = "import-setters"
path = "src/import/setters.rs"

[[bin]]
name = "import-operations"
path = "src/import/operations.rs"

[[bin]]
name = "reentrancy-simple-function"
path = "src/reentrancy/simple_function.rs"

[[bin]]
name = "reentrancy-getters"
path = "src/reentrancy/getters.rs"

[[bin]]
name = "reentrancy-setters"
path = "src/reentrancy/setters.rs"

[[bin]]
name = "reentrancy-operations"
path = "src/reentrancy/operations.rs"

[[bin]]
name = "reentrancy-global-state"
path = "src/reentrancy/global_state.rs"

[dependencies]
wit-bindgen = { version = "0.7.0", features = ["macros"] }
