[package]
name = "task-processor"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[dependencies]
async-graphql.workspace = true
linera-sdk.workspace = true
serde.workspace = true

[dev-dependencies]
linera-sdk = { workspace = true, features = ["test"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
insta.workspace = true
serde-reflection.workspace = true

[[bin]]
name = "task_processor_contract"
path = "src/contract.rs"

[[bin]]
name = "task_processor_service"
path = "src/service.rs"
