[book]
authors = ["Linera"]
language = "en"
multilingual = false
src = "../docs"
description = "The Linera Manual"

[output.html]
default-theme = "Light"
default-dark-theme = "Light"
additional-css = ["theme/theme.css", "./mdbook-admonish.css"]
additional-js = ["custom.js", "mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/linera-io/linera-protocol"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/linera-io/linera-protocol/edit/main/{path}"
hash-files = true
no-section-label = true

[output.html.fold]
enable = true
level = 0

[output.html.playground]
runnable = false

[output.html.redirect]
"/overview.html" = "/core_concepts/overview.html"
"/core_concepts.html" = "/core_concepts/overview.html"
"/developers.html" = "/developers/getting_started.html"
"/operators.html" = "/operators/devnets.html"

[output.linkcheck]
optional = true
follow-web-links = false
exclude = [ 'x\.com', 'crates\.io', 'npmjs\.com' ]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.0.3" # do not edit: managed by `mdbook-admonish install`

[build]
build-dir = "book"
create-missing = false
use-default-preprocessors = true

