[package]
name = "linera-chain"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[features]
test = ["tokio/macros"]

[dependencies]
async-trait = "0.1.52"
bcs = "0.1.3"
futures = "0.3.17"
linera-base = { path = "../linera-base" }
linera-execution = { path = "../linera-execution" }
linera-views = { path = "../linera-views" }
log = "0.4.14"
rocksdb = "0.19.0"
serde = { version = "1.0.130", features = ["derive"] }
tokio = "1.12.0"

[dev-dependencies]
linera-chain = { path = ".", features = ["test"] }
linera-base = { path = "../linera-base", features = ["test"] }
