[package]
name = "linera-chain"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[features]
test = ["tokio/macros"]

[dependencies]
async-trait = "0.1.52"
async-graphql = "5.0.5"
linera-base = { path = "../linera-base" }
linera-execution = { path = "../linera-execution", default-features = false }
linera-views = { path = "../linera-views" }
log = "0.4.14"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.31"
tokio = "1.12.0"

[dev-dependencies]
linera-base = { path = "../linera-base", features = ["test"] }

[package.metadata.cargo-machete]
ignored = ["async-trait"]
