[package]
name = "zef-core"
version = "0.1.0"
authors = ["Zefchain <devops@zefchain.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.52"
dyn-clone = "1.0.4"
futures = "0.3.17"
rand = "0.7.3"
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.12.0", features = ["full"] }
log = "0.4.14"

zef-base = { path = "../zef-base" }
zef-storage = { path = "../zef-storage" }
