server_config_path = "server_1.json"
host = "34.151.215.158"
port = 19100
internal_host = "validator-1"
internal_port = 20100
external_protocol = "Grpc"
internal_protocol = "Grpc"

# If deploying to GCP, host should be the Kubernetes pod name
[[shards]]
host = "server-1-shard-0"
port = 19100
metrics_host = "server-1-shard-0"
metrics_port = 21100

[[shards]]
host = "server-1-shard-1"
port = 19100
metrics_host = "server-1-shard-1"
metrics_port = 21100

[[shards]]
host = "server-1-shard-2"
port = 19100
metrics_host = "server-1-shard-2"
metrics_port = 21100

[[shards]]
host = "server-1-shard-3"
port = 19100
metrics_host = "server-1-shard-3"
metrics_port = 21100
