[package]
name = "counter"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[dependencies]
async-graphql = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
linera-sdk = { workspace = true }
linera-views = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
linera-sdk = { workspace = true, features = ["test"] }
webassembly-test = { workspace = true }

[[bin]]
name = "counter_contract"
path = "src/contract.rs"

[[bin]]
name = "counter_service"
path = "src/service.rs"