[package]
name = "linera-indexer-example"
version = "0.11.0"
description = "Indexer example."
authors = ["Linera <contact@linera.io>"]
readme = "README.md"
repository = "https://github.com/linera-io/linera-protocol"
homepage = "https://linera.io"
documentation = "https://docs.rs/linera-indexer/latest/linera_indexer/"
license = "Apache-2.0"
edition = "2021"

[features]
default = ["rocksdb"]
benchmark = ["linera-base/test", "linera-indexer/benchmark"]
rocksdb = ["linera-indexer/rocksdb", "linera-indexer-plugins/rocksdb"]
aws = ["linera-indexer/aws", "linera-indexer-plugins/aws"]
scylladb = ["linera-indexer/scylladb", "linera-indexer-plugins/scylladb"]
wasmer = ["linera-indexer-plugins/wasmer"]
wasmtime = ["linera-indexer-plugins/wasmtime"]
test = ["linera-service/test"]

[dependencies]
linera-indexer.workspace = true
linera-indexer-plugins.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing-subscriber = { workspace = true, features = ["fmt"] }

[dev-dependencies]
anyhow.workspace = true
async-graphql.workspace = true
linera-base.workspace = true
linera-indexer-graphql-client.workspace = true
linera-service = { workspace = true, features = ["rocksdb", "test"] }
linera-service-graphql-client.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
test-case.workspace = true
test-log = { workspace = true, features = ["trace"] }
tracing.workspace = true

[[bin]]
name = "linera-indexer"
path = "src/main.rs"
