[workspace]
[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
reqwest = { version = "0.11.24", default-features = false, features = [
    "rustls-tls",
] }
rig-core = "0.7.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
url = "2.4"

[package.metadata.cargo-machete]
ignored = ["rig-core"]
