[package]
name = "linera-faucet-service"
description = "Standalone faucet service for the Linera protocol."
documentation = "https://docs.rs/linera-faucet-service/latest/linera_faucet_service/"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[features]
default = ["wasmer"]
wasmer = [
    "linera-client/wasmer",
    "linera-execution/wasmer",
    "linera-storage/wasmer",
]
wasmtime = [
    "linera-client/wasmtime",
    "linera-execution/wasmtime",
    "linera-storage/wasmtime",
]
metrics = [
    "linera-base/metrics",
    "linera-client/metrics",
    "linera-faucet-server/metrics",
]

[[bin]]
name = "linera-faucet"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono = { workspace = true, features = ["clock"] }
clap.workspace = true
is-terminal.workspace = true
linera-base.workspace = true
linera-client = { workspace = true, features = ["fs"] }
linera-execution = { workspace = true, features = ["fs"] }
linera-faucet-server.workspace = true
linera-persistent.workspace = true
linera-service.workspace = true
linera-storage.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["fmt"] }

[build-dependencies]
cfg_aliases.workspace = true
