[package]
name = "linera-faucet-server"
description = "The server component of the Linera faucet."
readme = "README.md"
documentation = "https://docs.rs/linera-faucet-server/latest/linera_faucet_server/"

version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[package.metadata.cargo-machete]
ignored = ["prometheus"]

[features]
metrics = ["prometheus", "linera-base/metrics", "linera-client/metrics"]

[build-dependencies]
cfg_aliases.workspace = true

[dependencies]
anyhow.workspace = true
async-graphql.workspace = true
async-graphql-axum.workspace = true
axum.workspace = true
futures.workspace = true
linera-base.workspace = true
linera-chain.workspace = true
linera-client.workspace = true
linera-core.workspace = true
linera-execution.workspace = true
linera-metrics.workspace = true
linera-storage.workspace = true
linera-version.workspace = true
prometheus = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower-http = { workspace = true, features = ["cors"] }
tracing.workspace = true

[dev-dependencies]
async-trait.workspace = true
derive_more.workspace = true
linera-views.workspace = true
tempfile.workspace = true
[dev-dependencies.linera-core]
features = ["test"]
workspace = true
