[package]
name = "check_copyright_header"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[dependencies]
thiserror.workspace = true

[[bin]]
name = "check_copyright_header"
path = "src/main.rs"
