steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "docker"
    env:
      - "DOCKER_BUILDKIT=1"
    args:
      [
        "build",
        "-t",
        "${_IMAGE_PATH}",
        "-t",
        "${_IMAGE_NAME_SHORT_COMMIT}",
        "-t",
        "${_IMAGE_NAME_LONG_COMMIT}",
        "-f",
        "docker/Dockerfile.indexer",
        ".",
        "--build-arg",
        "git_commit=${_GIT_COMMIT}",
        "--build-arg",
        "build_date=${_BUILD_DATE}",
        "--build-arg",
        "build_flag=${_BUILD_FLAG}",
        "--build-arg",
        "build_folder=${_BUILD_FOLDER}"
      ]
images:
  - "${_IMAGE_PATH}"
  - "${_IMAGE_NAME_SHORT_COMMIT}"
  - "${_IMAGE_NAME_LONG_COMMIT}"
