global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'proxy'
    static_configs:
      - targets: ['proxy:21100']

  - job_name: 'shards'
    static_configs:
      - targets:
        - 'docker-shard-1:21100'
        - 'docker-shard-2:21100'
        - 'docker-shard-3:21100'
        - 'docker-shard-4:21100'
