apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-auth-secret
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.grafanaCloudUsername | quote }}
  password: {{ .Values.grafanaCloudAPIToken | quote }}
