apiVersion: v1
kind: Service
metadata:
  name: shards
  labels:
    app: shards
spec:
  ports:
    - port: 19100
      name: http
  clusterIP: None
  selector:
    app: shards
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shards
spec:
  serviceName: "shards"
  replicas: 10
  selector:
    matchLabels:
      app: shards
  volumeClaimTemplates:
    - metadata:
        name: rocksdb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 100Mi
  template:
    metadata:
      labels:
        app: shards
    spec:
      serviceAccountName: linera-admin
      terminationGracePeriodSeconds: 10
      containers:
        - name: linera-server
          image: {{ .Values.lineraImage }}
          imagePullPolicy: {{ .Values.lineraImagePullPolicy }}
          command: ["./server-entrypoint.sh"]
          volumeMounts:
          - name: rocksdb
            mountPath: /usr/share/rocksdb
          env:
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      initContainers:
        - name: linera-server-initializer
          image: {{ .Values.lineraImage }}
          imagePullPolicy: {{ .Values.lineraImagePullPolicy }}
          command: ["./linera-server"]
          args:
            [
              "initialize",
              "--storage",
              "rocksdb:/usr/share/rocksdb/shard_data.db",
              "--genesis",
              "genesis.json",
            ]
          volumeMounts:
          - name: rocksdb
            mountPath: /usr/share/rocksdb
          env:
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: shards
  labels:
    team: infra
spec:
  selector:
    matchLabels:
      app: shards
  podMetricsEndpoints:
  - port: http
    path: /metrics
    scheme: http
