apiVersion: v1
kind: Service
metadata:
  name: shards
  labels:
    app: shards
spec:
  ports:
    - port: 19100
      name: http
    - port: 21100
      name: metrics
  clusterIP: None
  selector:
    app: shards
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shards
spec:
  serviceName: "shards"
  replicas: {{ .Values.numShards }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: shards
  template:
    metadata:
      labels:
        app: shards
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: linera-server-initializer
          image: {{ .Values.lineraImage }}
          imagePullPolicy: {{ .Values.lineraImagePullPolicy }}
          command: ["./server-init.sh", {{ .Values.storage | quote }}, {{ .Values.storageReplicationFactor | quote }}]
          env:
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
            - name: RUST_BACKTRACE
              value: "1"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otelExporterEndpoint }}
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
            {{- if .Values.dualStore }}
            - name: linera-db
              mountPath: "/linera.db"
            {{- end }}
      containers:
        - name: linera-server
          image: {{ .Values.lineraImage }}
          imagePullPolicy: {{ .Values.lineraImagePullPolicy }}
          command: ["./server-entrypoint.sh", {{ .Values.storage | quote }}, {{ .Values.storageReplicationFactor | quote }}]
          env:
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otelExporterEndpoint }}
            {{- if .Values.serverTokioThreads }}
            - name: LINERA_SERVER_TOKIO_THREADS
              value: "{{ .Values.serverTokioThreads }}"
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
            {{- if .Values.dualStore }}
            - name: linera-db
              mountPath: "/linera.db"
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: validator-config
            items:
              - key: serverConfig
                path: server.json
              - key: genesisConfig
                path: genesis.json
  {{- if .Values.dualStore }}
  volumeClaimTemplates:
    - metadata:
        name: linera-db
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.usingLocalSsd }}
        storageClassName: nvme-ssd-block
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.rocksdbStorageSize }}
  {{- end }}
