apiVersion: v1
kind: Service
metadata:
  name: shards
  labels:
    app: shards
spec:
  ports:
    - port: 19100
      name: http
    - port: 21100
      name: metrics
  clusterIP: None
  selector:
    app: shards
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shards
spec:
  serviceName: "shards"
  replicas: {{ .Values.numShards }}
  selector:
    matchLabels:
      app: shards
  template:
    metadata:
      labels:
        app: shards
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: linera-server-initializer
          image: {{ .Values.lineraImage }}
          imagePullPolicy: {{ .Values.lineraImagePullPolicy }}
          command: ["./server-init.sh"]
          env:
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
            - name: RUST_BACKTRACE
              value: "1"
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      containers:
        - name: linera-server
          image: {{ .Values.lineraImage }}
          imagePullPolicy: {{ .Values.lineraImagePullPolicy }}
          command: ["./server-entrypoint.sh"]
          env:
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: validator-config
            items:
              - key: serverConfig
                path: server.json
              - key: genesisConfig
                path: genesis.json
