[package]
name = "linera-views"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[features]
test = ["anyhow", "tokio/macros", "tokio/sync", "tokio/parking_lot"]

[dependencies]
anyhow = { version = "1.0.57", optional = true }
async-trait = "0.1.52"
aws-config = "0.14.0"
aws-sdk-dynamodb = "0.14.0"
aws-sdk-s3 = "0.14.0"
aws-smithy-http = "0.44.0"
aws-types = "0.14.0"
num-integer = "0.1.45"
bcs = "0.1.3"
dashmap = "5.3.4"
futures = "0.3.17"
generic-array = { version = "0.14.4", features = ["serde"] }
http = "0.2.7"
linera-base = { path = "../linera-base" }
log = "0.4.14"
paste = "1.0.8"
rocksdb = "0.19.0"
serde = { version = "1.0.130", features = ["derive"] }
sha2 = "0.9.8"
thiserror = "1.0.31"
tokio = "1.12.0"

[dev-dependencies]
linera-views = { path = ".", features = ["test"] }
tempfile = "3.2.0"
