[package]
name = "linera-views"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[dependencies]
anyhow = { version = "1.0.57", optional = true }
async-trait = "0.1.52"
bcs = "0.1.3"
futures = "0.3.17"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.31"
tokio = { version = "1.12.0", features = ["full"] }
log = "0.4.14"

[dev-dependencies]
anyhow = "1.0.57"
getset = "0.1.2"
