[package]
name = "linera-views"
version = "0.1.0"
description = "A library mapping complex data structures onto a key-value store, used by the Linera protocol"
authors = ["Linera <contact@linera.io>"]
readme = "README.md"
repository = "https://github.com/linera-io/linera-protocol"
homepage = "https://linera.io"
license = "Apache-2.0"
edition = "2021"

[features]
test = ["anyhow", "tokio/macros", "tokio/parking_lot"]
aws = ["aws-config", "aws-sdk-dynamodb", "aws-sdk-s3", "aws-smithy-http", "aws-types"]
db_timings = []
metrics = ["dep:hex", "dep:metrics"]

[dependencies]
static_assertions = "1.1.0"
async-lock = "2.6.0"
async-trait = "0.1.52"
bcs = "0.1.3"
futures = "0.3.17"
generic-array = { version = "0.14.4", features = ["serde"] }
hex = { version = "0.4.3", optional = true }
linera-base = { path = "../linera-base" }
linera-views-derive = { path = "../linera-views-derive" }
metrics = { version = "0.20.1", optional = true }
serde = { version = "1.0.130", features = ["derive"] }
sha3 = "0.10.6"
thiserror = "1.0.31"
linked-hash-map = "0.5.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.25.0", features = ["rt", "sync"] }
anyhow = { version = "1.0.57", optional = true }
tracing = "0.1.37"
http = "0.2.7"
rand = "0.8.5"
rocksdb = "0.19.0"
aws-config = { version = "0.14.0", optional = true }
aws-sdk-dynamodb = { version = "0.14.0", optional = true }
aws-sdk-s3 = { version = "0.14.0", optional = true }
aws-smithy-http = { version = "0.44.0", optional = true }
aws-types = { version = "0.14.0", optional = true }
tokio-test = "0.4.2"

[dev-dependencies]
linera-views = { path = ".", features = ["test"] }
tempfile = "3.2.0"
