[package]
name = "social"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[dependencies]
futures = "0.3.17"
async-trait = "0.1.52"
bcs = "0.1.3"
linera-sdk = { path = "../../linera-sdk" }
linera-views = { path = "../../linera-views" }
thiserror = "1.0.31"
serde = { version = "1.0.130", features = ["derive"] }

[dev-dependencies]
linera-sdk = { path = "../../linera-sdk", features = ["test"] }
webassembly-test = "0.1.0"

[[bin]]
name = "social_contract"
path = "src/contract.rs"

[[bin]]
name = "social_service"
path = "src/service.rs"
