[package]
name = "crowd-funding"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bcs = { workspace = true }
fungible = { workspace = true }
linera-sdk = { workspace = true }
linera-views = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[[bin]]
name = "crowd_funding_contract"
path = "src/contract.rs"

[[bin]]
name = "crowd_funding_service"
path = "src/service.rs"
