apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gke-raid-disks
  namespace: default
  labels:
    k8s-app: gke-raid-disks
spec:
  selector:
    matchLabels:
      name: gke-raid-disks
  template:
    metadata:
      labels:
        name: gke-raid-disks
    spec:
      nodeSelector:
        cloud.google.com/gke-local-nvme-ssd: "true"
      hostPID: true
      containers:
        - name: startup-script
          image: registry.k8s.io/startup-script:v2
          securityContext:
            privileged: true
          env:
            - name: STARTUP_SCRIPT
              value: |
                set -o errexit
                set -o nounset
                set -o pipefail

                # Ensure we have the XFS tools
                if ! command -v mkfs.xfs >/dev/null; then
                  echo "mkfs.xfs not found! Installing xfsprogs..."
                  apt-get update
                  DEBIAN_FRONTEND=noninteractive \
                    apt-get install -y --no-install-recommends xfsprogs
                fi

                devices=()
                for ssd in /dev/disk/by-id/google-local-ssd-block*; do
                  if [ -e "${ssd}" ]; then
                    devices+=("${ssd}")
                  fi
                done
                if [ "${#devices[@]}" -eq 0 ]; then
                  echo "No Local NVMe SSD disks found."
                  exit 1
                fi

                seen_arrays=(/dev/md/*)
                device=${seen_arrays[0]}
                echo "Setting RAID array with Local SSDs on device ${device}"
                if [ ! -e "$device" ]; then
                  device="/dev/md/0"
                  echo "y" | mdadm --create "${device}" --level=0 --force --raid-devices=${#devices[@]} "${devices[@]}"
                fi

                if ! blkid "${device}" >/dev/null 2>&1 ; then
                  echo "Formatting '${device}'"
                  mkfs.xfs -f "${device}"
                fi

                mountpoint=/mnt/disks/raid
                mkdir -p "${mountpoint}"
                echo "Mounting '${device}' at '${mountpoint}'"
                mount -o discard,prjquota,noatime,nodiratime "${device}" "${mountpoint}"
                chmod a+w "${mountpoint}"
