[package]
name = "evm-bridge"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[features]
test = []

[dependencies]
alloy-primitives.workspace = true
async-graphql.workspace = true
fungible.workspace = true
hex.workspace = true
linera-bridge = { path = "../../linera-bridge", default-features = false, features = ["chain"] }
linera-sdk.workspace = true
serde.workspace = true
wrapped-fungible.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
alloy-primitives.workspace = true
alloy-rlp = "0.3.12"
alloy-trie = "0.9.0"
async-graphql.workspace = true
fungible = { workspace = true, features = ["test"] }
linera-bridge = { path = "../../linera-bridge", default-features = false, features = ["chain"] }
linera-sdk = { workspace = true, features = ["test", "wasmer"] }
tokio.workspace = true
wrapped-fungible.workspace = true

[[bin]]
name = "evm_bridge_contract"
path = "src/contract.rs"

[[bin]]
name = "evm_bridge_service"
path = "src/service.rs"
