[package]
name = "zef-base"
version = "0.1.0"
authors = ["Zefchain <devops@zefchain.com>"]
edition = "2021"

[dependencies]
bcs = "0.1.3"
bincode = "1.3.3"
failure = "0.1.8"
generic-array = { version = "0.14.4", features = ["serde"] }
hex = "0.4.3"
rand = "0.7.3"
serde = { version = "1.0.130", features = ["derive"] }
ed25519 = "1.2.0"
ed25519-dalek = { version = "1.0.1", features = ["batch", "serde"] }
serde_json = "1.0.68"
serde-name = "0.2.0"
sha2 = "0.9.8"
structopt = "0.3.23"

[dev-dependencies]
similar-asserts = "1.1.0"
serde-reflection = "0.3.5"
serde_yaml = "0.8.21"

[[example]]
name = "generate-format"
path = "src/generate_format.rs"
test = false
