[package]
name = "linera-indexer-graphql-client"
description = "GraphQL client for the indexer"
readme = "README.md"
documentation = "https://docs.rs/linera-indexer-graphql-client/latest/linera_indexer_graphql_client/"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
graphql_client = { version = "0.13", features = ["reqwest-rustls"] }
linera-base.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
linera-execution.workspace = true

[dev-dependencies]
linera-service.workspace = true
tempfile.workspace = true
test-log = { workspace = true, features = ["trace"] }
tokio = { workspace = true, features = ["full", "test-util"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["fmt"] }
