# Values for charts linera-validator for the dev validator on GCP.

lineraImage: us-docker.pkg.dev/linera-io-dev/linera-docker-repo/zefchain-gcp-test:0.1
lineraImagePullPolicy: Always
logLevel: "info"
