[package]
name = "linera-sdk-wasm-tests"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[dev-dependencies]
async-trait = "0.1.74"
bcs = "0.1.6"
futures = "0.3.29"
linera-sdk = { path = "..", features = ["test"] }
linera-views = { path = "../../linera-views" }
log = "0.4.20"
webassembly-test = "0.1.0"
