[package]
name = "reentrant-counter"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bcs = { workspace = true }
futures = { workspace = true }
linera-sdk = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
linera-sdk = { workspace = true, features = ["test"] }
webassembly-test = { workspace = true }

[[bin]]
name = "reentrant-counter_contract"
path = "src/contract.rs"

[[bin]]
name = "reentrant-counter_service"
path = "src/service.rs"
