[package]
name = "wrapped-fungible"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[features]
test = []

[dependencies]
async-graphql.workspace = true
fungible.workspace = true
futures.workspace = true
hex.workspace = true
linera-sdk.workspace = true
serde.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
async-graphql.workspace = true
fungible = { workspace = true, features = ["test"] }
linera-sdk = { workspace = true, features = ["test", "wasmer"] }
tokio.workspace = true

[[bin]]
name = "wrapped_fungible_contract"
path = "src/contract.rs"

[[bin]]
name = "wrapped_fungible_service"
path = "src/service.rs"
