[package]
name = "non-fungible"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[features]
test = []

[dependencies]
async-graphql.workspace = true
base64.workspace = true
bcs.workspace = true
fungible.workspace = true
linera-sdk.workspace = true
serde.workspace = true
sha3.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
serde-reflection.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
fungible = { workspace = true, features = ["test"] }
insta.workspace = true
linera-sdk = { workspace = true, features = ["test", "wasmer"] }
non-fungible = { workspace = true, features = ["test"] }
serde-reflection.workspace = true
tokio.workspace = true

[[bin]]
name = "non_fungible_contract"
path = "src/contract.rs"

[[bin]]
name = "non_fungible_service"
path = "src/service.rs"
