[package]
name = "social"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[dependencies]
async-graphql.workspace = true
bcs.workspace = true
linera-sdk.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
linera-sdk = { workspace = true, features = ["test", "wasmer"] }
tokio = { workspace = true, features = ["rt", "sync"] }

# TODO(#1970): Remove once macros don't depend on them
[package.metadata.cargo-machete]
ignored = ["serde_json"]

[[bin]]
name = "social_contract"
path = "src/contract.rs"

[[bin]]
name = "social_service"
path = "src/service.rs"
