server_config_path = "server_3.json"
host = "127.0.0.1"
port = 9300
internal_host = "127.0.0.1"
internal_port = 10300
metrics_host = "127.0.0.1"
metrics_port = 11300
external_protocol = "Grpc"
internal_protocol = "Grpc"

[[shards]]
host = "127.0.0.1"
port = 9301

[[shards]]
host = "127.0.0.1"
port = 9302

[[shards]]
host = "127.0.0.1"
port = 9303

[[shards]]
host = "127.0.0.1"
port = 9304