[package]
name = "linera-sdk"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[package.metadata.cargo-udeps.ignore]
development = ["linera-sdk"]

[features]
test = []

[dependencies]
async-trait = "0.1.52"
bcs = "0.1.3"
custom_debug_derive = "0.5.0"
futures = "0.3.17"
log = "0.4.14"
serde = { version = "1.0.130", features = ["derive"] }
serde_with = "2.1.0"
linera-base = { path = "../linera-base" }
linera-views = { path = "../linera-views" }
thiserror = { version = "1.0.31" }
wit-bindgen-guest-rust = { git = "https://github.com/jvff/wit-bindgen", rev = "4f25d5363360c049e3415c32f5654faea5f874ce" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow = "1.0.57"
tokio = "1.25.0"
wasmtime = "1.0"
