[package]
name = "linera-sdk"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[package.metadata.cargo-udeps.ignore]
development = ["linera-sdk"]

[features]
crypto = ["ed25519-dalek", "generic-array", "hex", "serde-name", "sha2", "thiserror"]
test = []

[dependencies]
async-trait = "0.1.52"
bcs = "0.1.3"
ed25519-dalek = { version = "1.0.1", features = ["batch", "serde"], optional = true }
futures = "0.3.17"
generic-array = { version = "0.14.4", features = ["serde"], optional = true }
hex = { version = "0.4.3", optional = true }
log = "0.4.14"
serde = { version = "1.0.130", features = ["derive"] }
serde-name = { version = "0.2.0", optional = true }
serde_with = "2.1.0"
sha2 = { version = "0.9.8", optional = true }
thiserror = { version = "1.0.31", optional = true }
wit-bindgen-guest-rust = { git = "https://github.com/jvff/wit-bindgen", rev = "4a9e7cc6899a9736e2a2d23dcfc4f8744b6107a1" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow = "1.0.57"
wasmtime = "0.39.1"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
linera-sdk = { path = ".", features = ["test"] }
thiserror = "1.0.31"
webassembly-test = "0.1.0"

[[example]]
name = "counter_contract"
path = "examples/counter/contract.rs"
crate-type = ["cdylib"]

[[example]]
name = "counter_service"
path = "examples/counter/service.rs"
crate-type = ["cdylib"]

[[example]]
name = "crowd_funding_contract"
path = "examples/crowd-funding/contract.rs"
crate-type = ["cdylib"]
required-features = ["crypto"]

[[example]]
name = "crowd_funding_service"
path = "examples/crowd-funding/service.rs"
crate-type = ["cdylib"]
required-features = ["crypto"]

[[example]]
name = "fungible_contract"
path = "examples/fungible/contract.rs"
crate-type = ["cdylib"]
required-features = ["crypto"]

[[example]]
name = "fungible_service"
path = "examples/fungible/service.rs"
crate-type = ["cdylib"]
required-features = ["crypto"]
