[package]
name = "linera-sdk"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[dependencies]
async-trait = "0.1.52"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
bcs = "0.1.3"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.31"
wit-bindgen-guest-rust = { git = "https://github.com/jvff/wit-bindgen", rev = "4a9e7cc6899a9736e2a2d23dcfc4f8744b6107a1" }

[[example]]
name = "counter"
crate-type = ["cdylib"]
