[package]
name = "linera-sdk"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[package.metadata.cargo-udeps.ignore]
development = ["linera-sdk"]

[features]
wasmer = []
wasmtime = []
test = ["wasmer"]

[dependencies]
async-trait = "0.1.52"
bcs = "0.1.3"
custom_debug_derive = "0.5.0"
futures = "0.3.17"
log = "0.4.14"
serde = { version = "1.0.130", features = ["derive"] }
linera-base = { path = "../linera-base" }
linera-views = { path = "../linera-views" }
wit-bindgen-guest-rust = { git = "https://github.com/jvff/wit-bindgen", rev = "b3f43500ec4a65379b65148e32941117c17bc2f1" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow = "1.0.57"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
wasmtime = "1.0"
