[package]
name = "linera-sdk"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[package.metadata.cargo-udeps.ignore]
development = ["linera-sdk"]

[features]
wasmer = ["linera-core/wasmer", "linera-execution/wasmer", "linera-storage/wasmer"]
wasmtime = ["linera-core/wasmtime", "linera-execution/wasmtime", "linera-storage/wasmtime"]
test = []

[dependencies]
async-trait = { workspace = true }
bcs = { workspace = true }
custom_debug_derive = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
linera-base = { workspace = true }
linera-views = { workspace = true }
wit-bindgen-guest-rust = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow = { workspace = true }
cargo_toml = { workspace = true }
dashmap = { workspace = true }
linera-base = { workspace = true }
linera-chain = { workspace = true }
linera-core = { workspace = true, features = ["test"] }
linera-execution = { workspace = true }
linera-storage = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wasmtime = { workspace = true }
wit-bindgen-host-wasmtime-rust = { workspace = true }
