[package]
name = "linera-storage-service"
description = "RPC shared key value store."
documentation = "https://docs.rs/linera-storage-service/latest/linera_storage_service/"
readme = "README.md"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
metrics = ["linera-views/metrics"]
rocksdb = ["linera-views/rocksdb"]
storage-service = []
test = ["linera-views/test"]

[[bin]]
name = "linera-storage-server"
path = "src/server.rs"

[dependencies]
anyhow.workspace = true
async-lock.workspace = true
bcs.workspace = true
clap.workspace = true
linera-base.workspace = true
linera-version.workspace = true
linera-views.workspace = true
prost.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true, features = ["codegen", "prost", "transport"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["fmt"] }

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }
linera-storage-service = { path = ".", default-features = false, features = ["test"] }
proptest = { workspace = true, features = ["alloc"] }
serde-reflection.workspace = true
serde_yaml.workspace = true
similar-asserts.workspace = true
test-strategy.workspace = true

[build-dependencies]
cfg_aliases.workspace = true
tonic-build = { workspace = true, features = ["prost", "transport"] }

[package.metadata.cargo-machete]
ignored = ["proptest", "prost"]

[[bench]]
name = "store"
harness = false
