name: Indexer Tests

on:
  pull_request:
    branches:
      - "**"
  merge_group:
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs on pull requests
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.run_id }}'
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: full
  RUSTDOCFLAGS: -A rustdoc::redundant_explicit_links -D warnings
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

permissions:
  contents: read

jobs:
  indexer-check:
    runs-on: linera-io-self-hosted-ci
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Check indexer library compiles
      run: |
        cargo check --locked -p linera-indexer
    - name: Check indexer example compiles
      run: |
        cargo check --locked -p linera-indexer-example
    - name: Run indexer unit tests
      run: |
        cargo test --locked -p linera-indexer --lib -- --skip db::postgres

  indexer-integration-tests:
    if: github.event_name == 'merge_group' || github.event_name == 'workflow_dispatch'
    runs-on: linera-io-self-hosted-ci
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run indexer integration tests
      run: |
        cargo test --locked -p linera-indexer --lib
